config/routes.rb
CursoRuby::Application.routes.draw do
  resources :pins

  devise_for :users

  root to: 'pins#index'

  get 'users/:id' => 'users#show', as: :user

  get 'acerca' => 'sitio#acerca'

  

end

app/models/pin.rb
class Pin < ActiveRecord::Base		

	has_attached_file :image, styles: { medium: "320x240>"} 

	validates :description, presence: true
	validates_attachment :image, presence: true,
						content_type: { content_type: ['image/jpeg', 'image/jpg', 'image/png', 'image/gif']},
						size: { less_than: 5.megabytes }

	attr_accessible :user_id, :description, :image, :image_remote_url

	belongs_to :user	

	def image_remote_url=(url_value)
		self.image = URI.parse(url_value) unless url_value.blank?
		super
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable  

  devise :database_authenticatable, :registerable,
         :rememberable, :trackable, :validatable  

  has_many :pins

  attr_accessible :email, :password, :password_confirmation, :remember_me, :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_filter :configure_permitted_parameters, if: :devise_controller?

	protected
		def configure_permitted_parameters
		devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation) }
		devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:name, :email, :current_password, :password, :password_confirmation) }
	end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_filter :authenticate_user! , except: [:index]
  before_action :set_pin, only: [:show, :edit, :update, :destroy]

  # GET /pins
  # GET /pins.json
  def index
    @pins = Pin.order("created_at desc").page(params[:page]).per_page(10);

    respond_to do |format|
      format.html #index.html.erb
      format.json { render json: @pins }
      format.js
    end
  end

  # GET /pins/1
  # GET /pins/1.json
  def show
  end

  # GET /pins/new
  def new
    @pin = current_user.pins.new
  end

  # GET /pins/1/edit
  def edit
  end

  # POST /pins
  # POST /pins.json
  def create
    @pin = current_user.pins.new(pin_params)

    respond_to do |format|
      if @pin.save
        format.html { redirect_to @pin, notice: 'Pin was successfully created.' }
        format.json { render action: 'show', status: :created, location: @pin }
      else
        format.html { render action: 'new' }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pins/1
  # PATCH/PUT /pins/1.json
  def update
    respond_to do |format|
      if @pin.update(pin_params)
        format.html { redirect_to @pin, notice: 'Pin was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pins/1
  # DELETE /pins/1.json
  def destroy
    @pin.destroy
    respond_to do |format|
      format.html { redirect_to pins_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:description, :image, :image_file_name, :image_remote_url)
    end
end

app/controllers/sitio_controller.rb
class SitioController < ApplicationController
  def inicio
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  	@user = User.find(params[:id])
  	@pins = @user.pins.page(params[:page]).per_page(10);
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/helpers/sitio_helper.rb
module SitioHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
 
      <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
 
      <!-- Be sure to leave the brand out there if you want it shown -->
      <%= link_to "Curso Ruby", root_path, :class => "brand"%>
 
      <!-- Everything you want hidden at 940px or less, place within here -->
      <div class="nav-collapse collapse">

     		<ul class="nav">

  			  <li class="active">

  			  	<%= link_to "Inicio", root_path%>

  			  </li>

  			  <li>

  			  	<%= link_to "Acerca", acerca_path%>

  			  </li>

        </ul>

      </div> 
      <div class="nav-collapse collapse">

        <ul class="nav pull-right">

          <% if user_signed_in? %>

          <li>

            <%= link_to "Nuevo Recurso", new_pin_path %>

          </li>

          <li>

            <%= link_to "Perfil", edit_user_registration_path %>

          </li>

          <li>

            <%= link_to "Cerrar Sesión", destroy_user_session_path, :method => :delete %>

          </li>

          <% else %>

          <li>

            <%= link_to "Iniciar Sesión", new_user_session_path%>

          </li>

          <% end %>

        </ul>

      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CursoRuby</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%=render "layouts/header"%>

	<div class="container">

		<% flash.each do |name, msg|%>
			<%= content_tag(:div, msg, class: "alert alert-#(name)")%>
		<% end %>
  
		<%= yield %>		

	</div>

	<p>
		<%=render "sitio/footer"%>
	</p>

</body>
</html>

app/views/pins/_form.html.erb
<%= simple_form_for(@pin, html:{class: "form-horizontal"}) do |f| %>
  <%= f.error_notification %>
  <%= f.full_error :image_file_size, class: "alert alert-error"%>
  <%= f.full_error :image_content_type, class: "alert alert-error"%>

  	<%= f.input :image, :label => "Carga de Imágenes"%>

  	<%= f.input :image_remote_url, :label => "Imágen Cargada vía URL"%>

    <%= f.input :description, :label =>"Descripción", as: :text, input_html: {rows: "3"}%>

  <div class="actions">
    <%= f.button :submit, :class => "btn btn-primary" %>
  </div>
<% end %>

app/views/pins/edit.html.erb
<h1>Editar Recurso</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @pin %> |
<%= link_to 'Regresar', pins_path %>

app/views/pins/index.html.erb
<%= render 'sitio/inicio' %>
<div id='pins'>
  <%= render @pins %>
</div>
</br>
<p>
<%= will_paginate @posts %>
</p>

app/views/pins/index.js.erb
$boxes = $('<%= j render(@pins) %>')

$('#pins').append( $boxes ).imagesLoaded(function(){
	$('#pins').masonry('reload');
});

<% if @pins.next_page %>

	$('.pagination').replaceWith('<%= j will_paginate(@pins) %>');
<% else %>
	$('.pagination').remove();
<% end %>

app/views/pins/new.html.erb
<h1>Nuevo Recurso</h1>

<%= render 'form' %>

<%= link_to 'Regresar', pins_path %>

app/views/pins/show.html.erb
<div class = "row span6 offset3 well">
  

  <p>
  	<%= image_tag @pin.image %>
  </p>
  <strong>Descripci&oacute;n:</strong>
  <p>
  <%= @pin.description %>
  </p>
  <p>
  Creado por:<%= @pin.user.name %>
  </p>
</div>
<div class = "row span9">
<% if current_user == @pin.user %>
<%= link_to 'Editar', edit_pin_path(@pin) %>
<% end %> |
<%= link_to 'Regresar', pins_path %>
</div>

app/views/sitio/_footer.html.erb
<div class = "footer">
	<small>

		Curso creado por Carlos González.

	</small>
</div>

app/views/sitio/_inicio.html.erb
<% unless user_signed_in? %>

<div class="row">
  <div class="span9">

  		<div class="hero-unit">
		  	<h1>Curso Ruby on Rails</h1>
			  	<p>Ejemplo de Aplicaci&oacute;n utilizando el framework ruby on rails
						<%= link_to "Enlace a Oja.la", "http://oja.la"%>
						<%= link_to "Ruby on Rails", "http://rubyonrails.org"%>
				</p>
			  	<p>
		    		<%= link_to "Registrarse", new_user_registration_path, :class=> "btn btn-primary btn-large"%>
		  		</p>
		</div>
		
  </div>
</div>

<% end %>

app/views/sitio/acerca.html.erb
<h1>Curso Ruby on Rails</h1>
<p>P&aacute;gina Acerca de nosotros del curso de ruby on rails</p>
<%= link_to "Enlace a Oja.la", "http://oja.la"%>

app/views/sitio/inicio.html.erb
<% if user_signed_in? %>


<h2>Bienvenido de nuevo al sistema<h2>

<% else %>

<div class="row">
  <div class="span4">

  	<h2>Barra de Navegaci&oacute;n<h2>

  </div>
  <div class="span8">

  		<div class="hero-unit">
		  	<h1>Curso Ruby on Rails</h1>
			  	<p>Ejemplo de Aplicaci&oacute;n utilizando el framework ruby on rails
						<%= link_to "Enlace a Oja.la", "http://oja.la"%>
						<%= link_to "Ruby on Rails", "http://rubyonrails.org"%>
				</p>
			  	<p>
		    		<%= link_to "Registrarse", new_user_registration_path, :class=> "btn btn-primary btn-large"%>
		  		</p>
		</div>
		
  </div>
</div>

<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>
<div id='pins'>
  <%= render @pins %>
</div>
</br>
<p>
<%= will_paginate @pins %>
</p>